version: '3.8'

services:
  wordpress:
    # user: "${UID:-33}:${GID:-33}"
    # tmpfs:
    #   - /usr/local/docker/etc:uid=${UID:-33},gid=${GID:-33}
    #   - /var/run:uid=${UID:-33},gid=${GID:-33}
    depends_on:
      - db
    build: .
    image: phamhiep/wpsite:test
    # volumes:
    #   - ./config:/app/config
    #   - ./wp-content:/app/web/wp-content
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: not-so-secure
      WORDPRESS_DB_NAME: wordpress
      WP_ENV: development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: not-so-secure
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: not-so-secure
    ports:
      - 3307:3306

volumes:
    db_data: {}
